repository:
  name: "go-nimona"
  description: "Peer to peer networking library"
  homepage: "https://nimona.io/"
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: "master"
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false

labels:
  - name: "Good first issue"
    color: 0e8a16
  - name: "Help wanted"
    color: 7057ff
  - name: "Priority: Critical"
    color: b60205
  - name: "Priority: High"
    color: d93f0b
  - name: "Priority: Low"
    color: efe12a
  - name: "Priority: Medium"
    color: efbd2a
  - name: "Status: Abandoned"
    color: 000000
  - name: "Status: Available"
    color: caef2a
    oldname: to do
  - name: "Status: Blocked"
    color: ee0701
  - name: "Status: In Progress"
    color: fbca04
  - name: "Status: In Review"
    color: c41173
    oldname: review
  - name: "Status: On Hold"
    color: cccccc
  - name: "Status: Proposal"
    color: e03e9d
  - name: "Type: Bug"
    color: e99695
    oldname: bug
  - name: "Type: Documentation"
    color: d4c5f9
  - name: "Type: Enhancement"
    color: bfd4f2
    oldname: enhancement
  - name: "Type: Maintenance"
    color: c5def5
  - name: "Type: Question"
    color: c2e0c6
    oldname: question
