version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/nimona.io/go
    environment:
      CIRCLE_TEST_REPORTS: /tmp/test-reports
      CIRCLE_ARTIFACTS: /tmp/artifacts
      UPNP: false
      DEBUG_BLOCKS: true
      LOG_LEVEL: debug
      BIND_LOCAL: true
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            curl -L https://github.com/golang/dep/raw/master/install.sh | sh
            go get -u github.com/axw/gocov/gocov
            go get -u github.com/mattn/goveralls
            go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports/core
            mkdir -p $CIRCLE_ARTIFACTS
            go test ./... -race -v -coverprofile=$CIRCLE_ARTIFACTS/profile.out | go-junit-report > /tmp/test-reports/core/junit.xml
            sed -i "/_mock/d" $CIRCLE_ARTIFACTS/profile.out
            sed -i "/examples/d" $CIRCLE_ARTIFACTS/profile.out
            sed -i "/main/d" $CIRCLE_ARTIFACTS/profile.out
      # - run:
      #     name: Upload to coveralls
      #     command: goveralls -coverprofile=$CIRCLE_ARTIFACTS/profile.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-reports
      - run:
          name: Ensure code actually builds
          command: make build
  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/nimona.io/go
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            curl -L https://github.com/golang/dep/raw/master/install.sh | sh
            go get github.com/goreleaser/goreleaser
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Run goreleaser
          command: goreleaser
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)*/
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
