root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "PORT=3000 ./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "css"]
exclude_dir = ["tmp", "vendor"]
include_dir = []
exclude_file = []
exclude_unchanged = true
log = "./tmp/air.log"
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
